// your image label must match the appropriate alt to associate correctly
// adding or subtracting photos will require adjusting this


const altTextMap = {
    vinyl: {
        "1-vinyl-high": "White vinyl fence behind a gray garden shed, enclosing a green lawn amid mature foliage.",
        "2-vinyl-high": "White vinyl privacy fence with black hinges near a beige house, set against mature trees and autumn leaves.",
        "3-vinyl-high": "Long stretch of white vinyl fence in a backyard, with a small shed in the distance and neatly trimmed grass.",
        "4-vinyl-high": "Tall white vinyl privacy fence along a suburban lawn, leading to a storage shed and framed by lush greenery.",
        "5-vinyl-high": "White vinyl gate connecting the backyard to a side yard, featuring black hardware and a beige house backdrop.",
        "6-vinyl-high": "Gently curving white vinyl fence around a tree-lined backyard, offering a clean and durable boundary.",
        "7-vinyl-high": "Tall white vinyl fence bordering a corner property, with a house and chimney visible behind the enclosure.",
        "8-vinyl-high": "Expansive white vinyl fence curving along a driveway, providing a secure perimeter beneath towering trees.",
        "9-vinyl-high": "White vinyl privacy fence with a central gate, adding a neat and modern look to the property line.",
        "10-vinyl-high": "Large white vinyl fence on a corner lot, set against a bright blue sky and bordered by a manicured lawn."
    },
    craftsman: {
        "1-craftsman-high": "A double-door craftsman cedar fence gate with an extended arbor, set against a backdrop of mature trees.",
        "2-craftsman-high": "A high craftsman cedar fence running alongside a driveway, adjacent to a gray garage and neighboring homes.",
        "3-craftsman-high": "A tall craftsman cedar fence lining a sidewalk, shaded by large trees in a suburban neighborhood.",
        "4-craftsman-high": "A partial lattice-top craftsman cedar fence gate enclosing a driveway, next to a stucco house with a Tudor-style roof.",
        "5-craftsman-high": "A craftsman cedar fence built on a short retaining wall encloses a stucco home’s corner yard, with a treehouse perched in the large oak tree overhead.",
        "6-craftsman-high": "A freshly installed craftsman cedar fence runs along the side of a property, with tall trees nearby.",
        "7-craftsman-high": "A backyard view featuring a craftsman cedar fence with decorative top rails and a central wooden gate.",
        "8-craftsman-high": "A spacious yard with raised metal garden beds, tree stumps, and a new craftsman cedar fence in the background.",
        "9-craftsman-high": "A suburban yard with a tall, natural-toned craftsman cedar fence providing privacy under leafy trees.",
        "10-craftsman-high": "A wide wooden gate with a curved top, framed by an arbor, forming part of the craftsman cedar fence.",
        "11-craftsman-high": "A long craftsman cedar fence with vertical planks, leading to a matching arched gate next to a blue house.",
        "12-craftsman-high": "A curved, double-door wooden gate set in a tall craftsman cedar fence, topped by a pergola-like arbor.",
        "13-craftsman-high": "A craftsman cedar fence with an arched gate positioned on a slight slope, connecting the yard to the driveway.",
        "14-craftsman-high": "A narrow walkway between a brick house and a tall craftsman cedar fence, ending at a wooden gate with an arbor.",
        "15-craftsman-high": "A corner property enclosed by a craftsman cedar fence with a smooth top rail, seen from an alley perspective.",
        "16-craftsman-high": "A craftsman-style cedar fence gate with a small arbor on top, surrounded by leafy trees near a red house.",
        "17-craftsman-high": "A manicured backyard bordered by a craftsman cedar fence, showcasing a variety of flowering plants.",
        "18-craftsman-high": "A tall craftsman cedar fence with horizontal accents, enclosing the yard of a light-colored home.",
        "19-craftsman-high": "A long stretch of craftsman cedar fencing along a residential street, providing privacy for the front yard.",
        "20-craftsman-high": "A neatly landscaped front yard with a craftsman cedar fence gate and an evergreen tree near the sidewalk.",
        "21-craftsman-high": "A wide, arched craftsman cedar fence gate topped by a pergola-like arbor, positioned beside a dark blue house.",
    },
    ornamental: {
        "1-ornamental-high": "Enclosed backyard featuring a black ornamental fence and gate, set against farmland and clear skies.",
        "2-ornamental-high": "Black ornamental fence with pine trees and a large gray home, bordering a sloping roadside lawn.",
        "3-ornamental-high": "Black ornamental fence enclosing a backyard next to a paved road, with wooded scenery and a waterway in the background.",
        "4-ornamental-high": "Black ornamental fence around a spacious suburban yard lined with evergreen trees, featuring a person near a raised deck.",
        "5-ornamental-high": "Black ornamental fence on a sloped lawn beside a two-story gray home with an elevated deck, showcasing autumn foliage.",
        "6-ornamental-high": "Black ornamental fence bordering a sidewalk in front of a tan duplex, accompanied by 'Sidewalk Closed' construction signs.",
        "7-ornamental-high": "Black ornamental fence gate between two houses, offering secure entry to a narrow gravel pathway.",
        "8-ornamental-high": "Black ornamental fence with a gate, set between a beige house and lush lawn, concealing an AC unit and side yard.",
        "9-ornamental-high": "Black ornamental fence gate leading to a red two-story home’s backyard, with a neatly paved walkway and green lawn.",
        "10-ornamental-high": "Black ornamental fence along a wooded shoreline, providing an open view of a calm river or lake through the trees.",
        "11-ornamental-high": "Black ornamental fence enclosing a backyard garden next to a white multi-level home, located in a suburban development.",
        "12-ornamental-high": "Black ornamental fence with a gated entry along a narrow side yard, adjacent to a house and retaining wall, with lush green lawn and wetlands in the background.",
        "13-ornamental-high": "Close-up of a black ornamental fence and gate near a retaining wall, showcasing a landscaped backyard and wetland backdrop.",
        "14-ornamental-high": "Long run of black ornamental fencing enclosing a gently sloping yard, overlooking expansive rural fields under a cloudy sky.",
        "15-ornamental-high": "View from a covered patio of a spacious backyard, bordered by a black ornamental fence and open countryside beyond.",
        "16-ornamental-high": "Black ornamental fence on a hillside, separating a backyard from wide-open fields in the distance.",
        "17-ornamental-high": "Black ornamental fence running along a sloped property behind a gray multi-story home, with wetlands and open land in the background.",
        "18-ornamental-high": "Black ornamental fence surrounding a suburban backyard alongside a concrete walkway, with a two-story home and evergreen trees in view.",
        "19-ornamental-high": "Neatly maintained backyard enclosed by a black ornamental fence, bordered by young evergreens and a wooded area beyond.",
        "20-ornamental-high": "Black ornamental fence installed along a gently sloping lawn, partially covered in melting snow, with a raised deck and neighboring fences in the background."
    },
    custom: {
        "1-custom-high": "A modern custom cedar fence with black metal posts and a decorative top rail, running along a sidewalk.",
        "2-custom-high": "A custom cedar fence with a black chain-link base and a flat top, running alongside a tan house with a wooden porch.",
        "3-custom-high": "A custom cedar fence gate with an arbor and a mix of wood slats and chain-link fencing, facing a modern home across the street.",
        "4-custom-high": "A front yard enclosed by a custom cedar fence with chain-link sections and a decorative wooden gate with an arbor.",
        "5-custom-high": "A side view of a custom cedar fence with chain-link panels and a secure wooden gate, enclosing a suburban front yard.",
        "6-custom-high": "A custom cedar fence with wavy pickets encloses a corner property, adding a decorative element to the streetscape.",
        "7-custom-high": "A close-up of the custom cedar fence with staggered-height pickets, following the curve of a landscaped front yard.",
        "8-custom-high": "An interior view of a custom cedar fence with wavy pickets, enclosing a garden with bare soil and a bird feeder.",
        "9-custom-high": "A wooden picket-style custom cedar fence encloses a lush front yard garden, blending with the surrounding greenery.",
        "10-custom-high": "A small back yard enclosed by a custom cedar fence with a chain-link base, featuring a pergola-style gate entrance.",
        "11-custom-high": "A custom cedar fence gate composed of horizontal wooden slats and black metal hardware, partially shaded by nearby trees."
    },
    standard: {
        "1-standard-high": "Standard cedar fence enclosing a pool area, blending seamlessly with a retaining wall and patio.",
        "2-standard-high": "Battenboard cedar fence along a suburban backyard, featuring a tall privacy design next to a house.",
        "3-standard-high": "Battenboard cedar fence with a landscaped garden, offering privacy and a natural wood aesthetic.",
        "4-standard-high": "Battenboard cedar fence behind blooming peonies, creating a warm and private backyard border.",
        "5-standard-high": "Long stretch of battenboard cedar fence running along a leafless treeline, showcasing a sturdy boundary.",
        "6-standard-high": "Standard cedar fence with an arched gate, providing secure entry to a side yard.",
        "7-standard-high": "Standard cedar fence beneath tall pine trees, adding privacy to a shaded residential driveway.",
        "8-standard-high": "Standard cedar fence lined by neatly trimmed shrubs and vibrant flowers, enhancing a suburban yard.",
        "9-standard-high": "Standard cedar fence with a wooded backdrop, creating a private boundary around a spacious backyard.",
        "10-standard-high": "Standard cedar fence surrounding a yard with mature trees, offering a natural and secure perimeter.",
        "11-standard-high": "Standard cedar fence gate spanning a driveway, with a blue house in the background, providing privacy and a natural wood boundary.",
    },
    chainLink: {
        "1-chainLink-high": "Black chain link fence around a backyard recreation area near a dark gray house, featuring a basketball pad and a children’s playset.",
        "2-chain-link-high": "Black chain link fence beside a beige house with a chimney, lightly dusted with snow in a suburban yard.",
        "3-chain-link-high": "Black chain link fence stretching through a leaf-strewn backyard, bearing a Nate’s Fence & Gate sign amid light snowfall.",
        "4-chain-link-high": "Chain link enclosure around a small shed, surrounded by autumn leaves and a dusting of snow.",
        "5-chain-link-high": "Black chain link fence running alongside a raised garden bed and mature trees, separating two residential yards.",
        "6-chain-link-high": "Long black chain link fence bordering a house and garden area, with fallen leaves scattered on the ground.",
        "7-chain-link-high": "Black chain link gate next to a brick chimney, offering backyard access and framed by late-season foliage.",
        "8-chain-link-high": "Black chain link fence in front of a gray house, containing two dogs and flanked by planters on the driveway.",
        "9-chain-link-high": "Black chain link fence along a sloped yard with mature trees, creating a boundary near a beige house and shed.",
        "10-chain-link-high": "Black chain link fence with a person in a red superhero-style mask perched playfully on top, surrounded by autumn leaves.",
        "11-chain-link-high": "Large black chain link fence enclosing a spacious green lawn, bordered by a beige home and storage shed in the distance.",
        "12-chain-link-high": "Black chain link fence with a central gate near a beige house and a white birch tree, enclosing a green backyard with a storage shed.",
        "13-chain-link-high": "Black chain link fence gate in front of a gray house, containing two small dogs and framed by planters on a driveway.",
        "14-chain-link-high": "Chain link fence gate at the center of a spacious lawn, backed by dense greenery and mature trees.",
        "15-chain-link-high": "Black chain link fence surrounding a large backyard with a beige two-story home, featuring a chimney and elevated deck.",
        "16-chain-link-high": "Black chain link fence bordering a lawn with a wooded backdrop, providing an open view of the tree line.",
        "17-chain-link-high": "Black chain link fence running alongside a beige house and driveway, lightly covered by snow in a residential setting.",
        "18-chain-link-high": "Chain link fence enclosing a wide suburban lawn in a newer development, with multiple homes and a storage shed in view.",
        "19-chain-link-high": "Black chain link fence and gate near a gray home, with a white dog visible behind the fence and lush grass in the yard.",
        "20-chain-link-high": "Chain link fence gate in front of a single-story home, surrounded by trimmed shrubs and green lawn.",
        "21-chain-link-high": "Black chain link fence gate leading to a large backyard with a wooden playset, basketball hoop, and gray shed.",
        "22-chain-link-high": "Black chain link fence installed along a sloping lawn next to a beige two-story home, providing a boundary for the side yard.",
        "23-chain-link-high": "Chain link fence marked by orange flags on a gently sloped backyard, surrounded by multiple suburban homes.",
        "24-chain-link-high": "Black chain link fence enclosing a backyard with a pine tree and children’s play structures, offering a secure play area."
    },
    capAndTrim: {
        "1-capNtrim-high": "A tall, newly installed wooden fence lines a residential sidewalk on a sunny day, with a blue garage and green trees in the background.",
        // "2-capNtrim-high": "A newly installed wooden cap and trim fence with double gates, enclosing a backyard next to a white garage and a parked car.",
        // "3-capNtrim-high": "A tall wooden cap and trim fence stretches along a snowy driveway, backed by evergreen hedges and a neighboring house.",
        // "4-capNtrim-high": "A wooden cap and trim gate in a backyard, framed by potted flowers and house windows on a sunny day.",
        // "5-capNtrim-high": "A residential backyard enclosed by a wooden cap and trim fence, with a small lawn area and neighboring houses in view.",
        // "6-capNtrim-high": "A wooden cap and trim fence with a gently arched gate, enclosing a driveway between two neighboring houses.",
        // "7-capNtrim-high": "A long wooden cap and trim fence running along a corner lot, with a blue garage and power lines visible in the background.",

    },
    horizontal: {
        // "1-horizontal-high": "A side yard enclosed by a horizontal cedar fence, separating a light-colored home from a dark-sided house under leafy trees.",
        // "2-horizontal-high": "A horizontal cedar fence gate with black hinges, positioned between a stucco home and a side yard.",
        // "3-horizontal-high": "A tall horizontal cedar fence composed of evenly spaced boards, extending along a driveway toward a black garage.",
        // "4-horizontal-high": "An enclosed corner of a backyard with horizontal cedar fencing, shaded by mature trees.",
        // "5-horizontal-high": "A long run of horizontal cedar fencing enclosing a side yard, with a dark garage in the background.",
        // "6-horizontal-high": "A row of hostas growing along a horizontal cedar fence, separating two neighboring homes.",
        // "7-horizontal-high": "A double gate of horizontal cedar boards topped by a simple arbor, set at the end of a concrete path.",
        // "8-horizontal-high": "A backyard entrance with a horizontal cedar fence gate and pergola-style top, leading to a stucco house.",
        // "9-horizontal-high": "A horizontal cedar fence wrapping around a corner property, providing privacy between stucco walls and a driveway.",
        // "10-horizontal-high": "A partially see-through horizontal cedar fence section near a white garage, allowing light and visibility into the yard.",
        // "11-horizontal-high": "A corner of a horizontal cedar fence encloses a backyard, meeting at a garage and shed beneath a tall evergreen tree.",
        // "12-horizontal-high": "A long horizontal cedar fence with a pergola-style gate provides privacy along the sidewalk in front of a stucco and brick residence.",
        // "13-horizontal-high": "A view of a horizontal cedar fence with a pergola gate, seen in front of a brick and stucco building.",
        // "14-horizontal-high": "A corner gate in a horizontal cedar fence featuring closely spaced boards, creating a private enclosure near a beige house.",
        // "15-horizontal-high": "A horizontal cedar fence, partially hiding a basketball hoop and driveway, surrounds a backyard behind a single-story home.",
        // "16-horizontal-high": "A narrow backyard enclosed by a horizontal cedar fence, set between a dark blue house and a red garage under overhanging pines.",
        // "17-horizontal-high": "A modern horizontal cedar fence gate at the end of a concrete walkway, framed by an arbor between a dark house and a stone wall.",


    },
    hogwire: {
        "hogwire-high-1": "A simple cedar hogwire fence enclosing a spacious yard, with a white house visible in the distance.",
        // "1-hogwire-high": "A cedar hogwire fence frames the front yard of a stucco house, featuring an arbor-style gate near the sidewalk.",
        // "2-hogwire-high": "A close-up view of an arbor-topped cedar hogwire gate, leading up to a yellow stucco home.",
        // "3-hogwire-high": "A wide perspective of a yellow stucco house and its front yard enclosed by a cedar hogwire fence.",
        // "4-hogwire-high": "A simple cedar hogwire fence enclosing a spacious yard, with a white house visible in the distance.",
        // "5-hogwire-high": "A cedar hogwire fence gate with an arbor, installed on a slight slope next to a beige-sided home.",
        // "6-hogwire-high": "A backyard view of a cedar hogwire fence featuring a wide gate, standing between neighboring houses.",
        // "7-hogwire-high": "A large open lawn bordered by a cedar hogwire fence, with a wooded area beyond.",
        // "8-hogwire-high": "A cedar hogwire fence surrounding a green yard under mature trees, allowing a clear view of the property beyond."

    },
}

export default altTextMap